# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnnaX7fcj7fRmx3edukQqKja_7CRoADI
"""

import streamlit as st

st.set_page_config(page_title="Influencer Discovery", layout="wide")

st.image("assets/HOMEPAGE.jpg", use_column_width=True)

st.markdown("""
# Welcome to Influencer Discovery 🔍
Explore Instagram and YouTube influencers by niche and category.

Use the menu on the left to begin your journey.
""")

if st.button("🚀 Start Exploring"):
    st.switch_page("pages/2_search_page.py")
