# -*- coding: utf-8 -*-
"""2_Search_Page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc3Y_d6sWyH1z2pWUfpjlvL8lgWVlTnc
"""

import streamlit as st
import pandas as pd

@st.cache_data
def load_data():
    df = pd.read_excel("data/instagram_data.xlsx", sheet_name=0)
    yt = pd.read_excel("data/instagram_data.xlsx", sheet_name=1)
    yt = yt.rename(columns={"USERNAME": "username"})
    df = pd.merge(df, yt[["username", "subscribers"]], on="username", how="left")

    df["max_audience"] = df[["followers", "subscribers"]].max(axis=1)

    def classify_influencer(count):
        if count < 10_000:
            return "Nano"
        elif count < 100_000:
            return "Micro"
        elif count < 500_000:
            return "Mid-Tier"
        elif count < 1_000_000:
            return "Macro"
        elif count < 5_000_000:
            return "Mega"
        else:
            return "Celebrity"

    df["Influencer_Type"] = df["max_audience"].apply(classify_influencer)
    return df[df["status"] == "Success"]

df = load_data()

st.set_page_config(page_title="Search Influencers", layout="wide")
st.title("🔍 Discover Influencers by Niche & Category")

# --- Niche selection ---
niches = df["Niche"].dropna().unique().tolist()
st.subheader("Choose a Niche:")
cols = st.columns(3)
for i, niche in enumerate(niches):
    with cols[i % 3]:
        if st.button(niche):
            st.session_state["selected_niche"] = niche

# --- Influencer Type (Category) selection ---
if "selected_niche" in st.session_state:
    st.subheader(f"Choose Influencer Type in '{st.session_state['selected_niche']}'")

    influencer_types = df[df["Niche"] == st.session_state["selected_niche"]]["Influencer_Type"].unique()
    type_cols = st.columns(4)
    for i, infl_type in enumerate(influencer_types):
        with type_cols[i % 4]:
            if st.button(infl_type):
                st.session_state["selected_category"] = infl_type
                st.switch_page("pages/3_List_Page.py")
else:
    st.info("Please select a Niche first.")