# -*- coding: utf-8 -*-
"""2_List_Page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc3Y_d6sWyH1z2pWUfpjlvL8lgWVlTnc
"""

import streamlit as st
import pandas as pd

@st.cache_data
def load_data():
    # Load Instagram data
    df = pd.read_excel("data/instagram_analysis_Fashion All (1) (1).xlsx", sheet_name=0)

    # Load YouTube data
    yt = pd.read_excel("data/instagram_analysis_Fashion All (1) (1).xlsx", sheet_name=1)
    yt = yt.rename(columns={"instagram_username": "username"})
     # Perform left merge to keep all Instagram users
    df = pd.merge(df, yt[["username", "subscribers"]], on="username", how="left")

    # Calculate max audience (using followers if no YouTube data)
    df["max_audience"] = df[["followers", "subscribers"]].max(axis=1)

    def classify_influencer(count):
        if count < 10_000:
            return "Nano"
        elif count < 100_000:
            return "Micro"
        elif count < 500_000:
            return "Mid-Tier"
        elif count < 1_000_000:
            return "Macro"
        elif count < 5_000_000:
            return "Mega"
        else:
            return "Celebrity"

    df["Influencer_Type"] = df["max_audience"].apply(classify_influencer)
    return df[df["status"] == "Success"]

df = load_data()

# Get filters from session state
niche = st.session_state.get("selected_niche")
infl_type = st.session_state.get("selected_category")

if not niche or not infl_type:
    st.warning("Please select both a Niche and Influencer Type.")
    st.stop()

st.set_page_config(page_title="Influencer List", layout="wide")
st.title(f"📋 Influencers - {niche} | {infl_type}")

# Apply filters
filtered_df = df[(df["Niche"] == niche) & (df["Influencer_Type"] == infl_type)]

if filtered_df.empty:
    st.info("No influencers found for the selected criteria.")
else:
    for _, row in filtered_df.iterrows():
        cols = st.columns([1, 3, 2, 2, 2])
        with cols[0]:
            if pd.notna(row["profile_pic_url"]):
                st.image(row["profile_pic_url"], width=60)
            else:
                st.image("https://via.placeholder.com/60", width=60)
        with cols[1]:
            st.markdown(f"**{row['username']}**")

        with cols[2]:
            st.metric("Instagram Followers", f"{int(row['followers']):,}" if not pd.isna(row['followers']) else "N/A")

        with cols[3]:
            # Only show YouTube metric if data exists
            if pd.notna(row['subscribers']):
                st.metric("YouTube Subscribers", f"{int(row['subscribers']):,}")
            else:
                st.write("No YouTube data")

        with cols[4]:
            st.write(f"**{row['Niche']}**")
            st.markdown(f"[📊 View Dashboard](?username={row['username']})")
        st.divider()
